---
- hosts: flatico
  # remote_user: yourname
  tasks:
    - git:
        repo: 'https://github.com/umate/flatico.git'
        dest: '/root/flatico'
        update: yes

    - name: Install Backend requirements
      shell: pip3 install -r requirements.txt
      args:
        executable: /bin/bash
        chdir: /root/flatico/backend

    - name: install web server service file
      template: src=templates/backend.j2 dest=/etc/systemd/system/flatico-backend.service
      become: true
      become_user: root
    # - name: make run.sh executable
    #   file:
    #     path: /root/flatico/backend/run.sh
    #     mode: "u=rwx,g=rx,o=rx"
    - name: restart web server
      systemd:
        state: restarted
        name: flatico-backend
        daemon_reload: yes
      become: true
      become_user: root
        # - name: change dir
    #   shell: cd flatico
    # - name: git pull
    #   shell: git pull origin master
    # - name: install packages
    #   shell: pip3 install -r backend/requirements.txt

    # - name: start web server
    #   shell: pytnon3 backend/app.py
